apiVersion: oort.ccs.guidewire.com/v1alpha1
kind: GatewayConfig
metadata:
  name: guestbook-ui
spec:
  profiles:
  - name: Default
  path_configs:
  - name: Default
    paths:
    - /
    profiles:
    - Default
  service_ref: guestbook-ui

